[tool.poetry]
name = "fastapistorediploma"
version = "0.1.0"
description = ""
authors = ["Nurlan-Grachyov <nurlan.grachyov@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
fastapi = { extras = ["all"], version = "^0.115.12" }
uvicorn = "^0.34.3"
tortoise-orm = "^0.25.1"
asyncpg = "^0.30.0"
flake8 = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
